services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sispet'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
